/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

//macros
#define SRAM_Start 0x20000000U
#define SRAM_Size (128*512)
#define SRAM_End (SRAM_Start) + (SRAM_Size)
#define STACK_Start SRAM_End

#define STACK_MSP_START STACK_Start


int fun_add (int a, int b, int c, int d){
		return a+b+c+d;
	}

int main(void)
{
	int ret;

	ret = fun_add (1,4,5,6);

	printf("Result = %d \n", ret);


	/* Loop forever */
	for(;;);
}
