/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *ptr = (uint32_t*) 0x20000200;
	*ptr = 0xff;

	//Normal Method
	*ptr &= ~(1<<7); //cLEAR THE 7TH BIT

	//Reset the value to 0Xff
	*ptr = 0xff;


	//Bit band Method
	uint8_t *alias_address =(uint8_t*) (0x22000000 +(32*(0x20000200-0x20000000))+28);
	*alias_address =0;

    /* Loop forever */
	for(;;);
}
